apiVersion: apps/v1
kind: Deployment
metadata:
  name: stedi-josueavila-dev
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: stedi-josueavila-dev
  template:
    metadata:
      labels:
        app: stedi-josueavila-dev
    spec:
      containers:
        - name: stedi-josueavila-dev
          image: gcr.io/bestteam362/josue-stedi-api
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-prod
                  key: REDIS_PASSWORD
            - name: REDIS_HOST
              value: "redis-stedi-prod"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 10
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: stedi-josueavila-nodeport
spec:
  selector:
    app: stedi-josueavila-dev
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-josueavila-certificate
spec:
  domains:
    - josueavila.cit262.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-josueavila-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: stedi-josue-public
    networking.gke.io/managed-certificates: stedi-josueavila-certificate
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stedi-josueavila-nodeport
            port:
              number: 80